### ISSUE TITLE
Rewrite HIR->MIR lowering to use Places

### ISSUE THREAD

**Issue by arora-aman** [rust-lang/project-rfc-2229#10]

**Comment by nikomatsakis** [comment]
An idea for how we might approach this (but not the only one)

```rust
let c = || use(foo.bar.baz, foo.bar.baz2);
```

This results in a HIR like:

* use()
    * field:baz // today: `self.0.bar.baz`
        * field:bar // today: `self.0.bar`
            * variable:foo // today returns a place like `self.0`

under new system:

* when we reach `foo`, we would look up in the map and get a set of minimum captured places 
* the `variable:foo` nodes must appear as a child of some subtree that is in that set
* whereas today MIR construction returns `(HIR node -> MIR place)`
    * it would return `(HIR node -> (MIR place | {upvar captures})`
* the `field:bar` node would get back a set of captures that is not a singleton set, narrow it down, and return it up
* the `field:baz` node would return the MIR place `self.0`

**Comment by arora-aman** [comment]
https://hackmd.io/aD41lqdMSmG7mvHJYt-mtg
