### ISSUE TITLE
Refactoring HIR Place: Fields

### ISSUE THREAD

**Issue by nikomatsakis** [rust-lang/project-rfc-2229#2]
As part of https://github.com/rust-lang/project-rfc-2229/issues/1, one of the first steps would be to extract out a "Field" projection for HIR Places.

To make this change, we would start by extending the [definition of `Projection`](https://github.com/rust-lang/rust/blob/feb3536eba10c2e4585d066629598f03d5ddc7c6/src/librustc_typeck/mem_categorization.rs#L76-L82) with a new variant, `Field`, based on the [MIR variant](https://doc.rust-lang.org/nightly/nightly-rustc/rustc_middle/mir/enum.ProjectionElem.html#variant.Field). 

XXX add more details

**Comment by arora-aman** [comment]
via https://github.com/rust-lang/rust/pull/74140
