### ISSUE TITLE
Handle patterns within closures with the feature gate enabled

### ISSUE THREAD

**Issue by arora-aman** [rust-lang/project-rfc-2229#24]
When `capture_disjoint_fields` is enabled we see that the compiler ICEs when closure contains something like 

```rust
let x = 10;
let tup = (1, 2);
let p = Point { x: 10, y: 20 };

let c = || {
    let _ = x;
    let Point { x, y } = p; // 1
    let (_, _) = tup; // 2
};
```

The problem here is that in case 1 `p[0]` and `p[1]` are captured, but when we build MIR we need to get information about the initializer which is `p` in this case which is missing since `p` itself isn't captured.

The issue with 2 is that since nothing from `tup` is used, nothing is captured. Nothing will be read when MIR is built either, but to build MIR we need access to `tup`, which we don't have.

Ensure `ui/closures/2229_closure_analysis/wild_patterns` passes

**Comment by roxelo** [comment]
Once this is implemented, also modify the [following test](https://github.com/sexxi-goose/rust/blob/b498870d9c992e61e0f7930f2679b091b5f2ddbc/src/test/ui/closures/2229_closure_analysis/diagnostics/closure-origin-single-variant-diagnostics.rs#L16-L21) so the closure body is:
```
let SingleVariant::Point(ref mut x, _) = point;
*x += 1;
```

**Comment by arora-aman** [comment]
Iniital ideas: https://hackmd.io/fgc31ECfQnaxfP9DmjgVNw?view

**Comment by arora-aman** [comment]
More detailed ideas using fake reads for "upvars": https://hackmd.io/fgc31ECfQnaxfP9DmjgVNw
