### ISSUE TITLE
base of an index projection is always captured

### ISSUE THREAD

**Issue by nikomatsakis** [rust-lang/project-rfc-2229#26]
In the following example ([playground](https://play.rust-lang.org/?version=nightly&mode=debug&edition=2018&gist=6cf3dd6d5c9490d58e282fe3515782b0)):

```rust
let foo = [1, 2, 3];
|| let _ = foo[0];
```

* ExprUseVisior sees `foo[0]` as an overloaded index operation
* It therefore considers `foo` to be used
* So the closure will capture `foo`

However, it would be *plausible*:

* because `foo[0]` is not overloaded, and `0` is constant, ec
* we could consider `foo[0]` as a place expression
* and thus ignore it because it is assigned to `_`
* and thus not capure `foo`

**Comment by arora-aman** [comment]
Just noting here that any change we make can potentially affect clippy. Also, change would really have to be made in `mem_categorization` because that's where we figure out the Place that is captured.

**Comment by nikomatsakis** [comment]
Arguments from the 2021-01-20 meeting:

* Capturing just `foo` is consistent with the borrow checker
    * You wouldn't be able to access `foo[1]` from outside the closure regardless
* Conceivably, if the element type were `Copy`, we could handle this case differently, but that would be complicated and would mean that adding a `T: Copy` bound changes the capture set of your closures in significant ways, which is surprising (admittedly, there are no destructors, and you're copying less data)
* We could change this later over a future edition if desired (or maybe we could even get away with it)

Conclusion: just capture `foo`
