### ISSUE TITLE
Auto traits with closures

### ISSUE THREAD

**Issue by arora-aman** [rust-lang/project-rfc-2229#29]
One way to use [AssertUnwindSafe](https://github.com/sexxi-goose/rust/blob/0d9651648d3b741e81ba7042e49a07b78a441517/library/std/src/panic.rs#L136-L194) is to do something like [test/mir_calls_to_shim](https://github.com/rust-lang/rust/blob/master/src/test/ui/mir/mir_calls_to_shims.rs#L23-L31). 

```rust
fn assert_panics<F>(f: F) where F: FnOnce() {
    let f = panic::AssertUnwindSafe(f);
    let result = panic::catch_unwind(move || {
        f.0()
    });
    if let Ok(..) = result {
        panic!("diverging function returned");
    }
}
```

This would not work once `capture_disjoint_fields` is enabled since `f.0` is captured, essentially rendering the wrapper redundant.

**Comment by nikomatsakis** [comment]
This is quite interesting, and similar to the problem where we capture subfields that are not `Clone` or entities which themselves *are* `Clone`

**Comment by arora-aman** [comment]
Similar issue with `Send` and `Sync`
https://github.com/rust-lang/rust/blob/de88bf148b122b27ce48a4a6679c41c834d33019/compiler/rustc_interface/src/util.rs#L121-L126

Here `run.0` isn't Send and Sync anymore.

**Comment by arora-aman** [comment]
https://doc.rust-lang.org/nightly/nightly-rustc/rustc_trait_selection/infer/struct.InferCtxt.html#method.predicate_may_hold

**Comment by arora-aman** [comment]
example code: https://github.com/rust-lang/rust/blob/0148b971c921a0831fbf3357e5936eec724e3566/compiler/rustc_trait_selection/src/autoderef.rs#L127-L138
