### ISSUE TITLE
Distinguish `Place` and `PlaceWithHirId`

### ISSUE THREAD

**Issue by nikomatsakis** [rust-lang/project-rfc-2229#3]
As part of refactoring to [the new HIR place](https://github.com/rust-lang/project-rfc-2229/blob/master/hir-place-target.md), we want to introduce a `PlaceWithHirId` that separates out the `hir_id` field from the rest of `Place`. 

We can do this by:

* rename the existing struct to `PlaceWithHirId`, get that to build
* refactor to extract a few fields out of `PlaceWithHirId` into a new struct, `Place`, get that to build
* Split projections into another structure, adding type information will be done as part of https://github.com/rust-lang/project-rfc-2229/issues/5

**Comment by arora-aman** [comment]
Outside of typechk `Place`s are only used within clippy, so far:

```
tools/clippy/clippy_lints/src/escape.rs
tools/clippy/clippy_lints/src/loops.rs
tools/clippy/clippy_lints/src/utils/usage.rs
```

Search details: https://github.com/sexxi-goose/rust/issues/14#issuecomment-638374305

**Comment by nikomatsakis** [comment]
That might be true, not sure. The compiler I think is mostly interested in finding the root variable at the moment, as those HIR places are (afaik) only used for the closure upvar analysis (within the compiler itself).

**Comment by arora-aman** [comment]
> That might be true, not sure. The compiler I think is mostly interested in finding the root variable at the moment, as those HIR places are (afaik) only used for the closure upvar analysis (within the compiler itself).

Sorry that was meant to be outside of typechk, the module it is defined in.

**Comment by arora-aman** [comment]
The markdown suggests using `PlaceReference` this might lead to someone confusing it for [`PlaceRef`](https://doc.rust-lang.org/nightly/nightly-rustc/rustc_middle/mir/struct.PlaceRef.html). 

My suggestion is `PlaceUnique`, `PlaceSpecific`. These aren't great so might need to come up with something better 😂

**Comment by nikomatsakis** [comment]
Ah, so *that* is what you meant by `PlaceUnique` on Zulip. =) 

I think I like `Place` and `PlaceWithHirId` best. Or perhaps `PlaceAccess`?

**Comment by nikomatsakis** [comment]
I found the "unique" terminology pretty confusing, and somehow assumed it was related to unique/mutable borrows or something else like that.

**Comment by arora-aman** [comment]
That is fair. `PlaceWithHirId` is quite descriptive, I like that. I just remember you suggesting coming up with something better on Zulip, that's why I suggested something else.
