### ISSUE TITLE
Move out of reference in move closures

### ISSUE THREAD

**Issue by arora-aman** [rust-lang/project-rfc-2229#31]
```rust
struct S {
    x: String,
    y: String
}

fn x(s: &mut S) {
    let mut c = move || {
        s.x.truncate(0);
    };
    c();
}


fn main() {
    let mut s = S { x: "".into(), y: "".into() };
    x(&mut s);
}
```

Without the feature gate `s` which is a `&mut S` is moved. However with the feature gate `*s.x` is moved which is a `String` which behind a `&mut S` and can't be moved out.

**Comment by nikomatsakis** [comment]
notes: https://hackmd.io/CdxyYchnRfyIxZHeykyvoA

**Comment by arora-aman** [comment]
Update from 2229 sync meeting:
- We drop any Derefs in case of move closures.

**Comment by arora-aman** [comment]
https://hackmd.io/PzxYMPY4RF-B9iH9uj9GTA

**Comment by arora-aman** [comment]
First part implemented here: https://github.com/rust-lang/rust/pull/80092
