### ISSUE TITLE
Incorrect diagnostic when the feature isn't enabled

### ISSUE THREAD

**Issue by ChrisPardy** [rust-lang/project-rfc-2229#39]
Compiling tte following code using the old capture logic
```rust
#![feature(rustc_attrs)]

struct S(i32);

fn foo() {
    let b = Box::new(S(10));
    
    let c = #[rustc_capture_analysis] || {
        let _b = b.0;
    };
    
    c();
}
```

prints the following diagnostic when compiled([view on playground](https://play.rust-lang.org/?version=nightly&mode=debug&edition=2018&gist=1f4748becb6031c1ffaf47c2175893a3)):
```
note: Min Capture b[] -> ImmBorrow
  --> src/lib.rs:9:39
   |
9  |       let c = #[rustc_capture_analysis] || {
   |  _______________________________________^
10 | |         let _b = b.0;
   | |                  ^^^ b[] captured as ImmBorrow here
11 | |     };
   | |_____^ b[] used here
```
It should instead look something like:
```
note: Min Capture b[] -> ImmBorrow
  --> /users/cpardy/example2.rs:10:18
   |
10 |         let _b = b.0;
   |                  ^^^
```

**Comment by arora-aman** [comment]
This only looks weird when debugging the compiler using `#[rustc_capture_analysis]` and indicates that the compiler didn't find a complete use of that path and was essentially faked. Users won't be impacted as fallback will be implemented by #8
