### ISSUE TITLE
Always make the "upvar types" a tuple of the actual upvar types (Parent issue#53488)

### ISSUE THREAD

**Issue by blitzerr** [rust-lang/project-rfc-2229#4]
**Updated by nikomatsakis with current status:**

In https://github.com/rust-lang/rust/pull/69968, @eddyb landed the "first step" here of introducing a tuple into the upvar types. However, in current rustc, we create that tuple "eagerly", as soon as we create the closure type:

https://github.com/rust-lang/rust/blob/1a87c49e33d87955e28fa92a8d59a17264ac6044/src/librustc_typeck/check/closure.rs#L90-L103

The next step is to move that tuple creation "late", so that it occurs during the "upvar analysis" code, so somewhere around here:

https://github.com/rust-lang/rust/blob/1a87c49e33d87955e28fa92a8d59a17264ac6044/src/librustc_typeck/check/upvar.rs#L194-L202

The problem with *this* is that the current accessor, [`ClosureSubsts::upvar_tys`](https://doc.rust-lang.org/nightly/nightly-rustc/rustc_middle/ty/struct.ClosureSubsts.html#method.upvar_tys), assumes that the upvar types are a tuple with known arity. Thus any calls to `upvar_tys` that occur before the upvar analysis code runs will ICE. 

Last time, we added an accessor `upvar_tuple_ty` that returned the *tuple itself* (or an unbound type variable), since it turned out that many of the calls to `upvar_tys` could be replaced by a call that operated on the tuple. Most notably, in the trait system, for example here:

https://github.com/rust-lang/rust/blob/1a87c49e33d87955e28fa92a8d59a17264ac6044/src/librustc_trait_selection/traits/select.rs#L2239-L2242

We changed this to yield the tuple always. The problem with *that* was that it was effecting the error messages, because the tuple was being introduced into the "backtrace" and we somehow never got things *quiite* right to remove it.

I still think that is perhaps the right approach, but there is an alternative we could try: we could get the tuple ty and check whether it's been "resolved" yet (via a call to [`self.infcx.shallow_resolve`](https://doc.rust-lang.org/nightly/nightly-rustc/rustc_infer/infer/struct.InferCtxt.html#method.shallow_resolve)). If so, we can put each of its components as we do today, but if not, we can return `Ambiguous`, [as we do here](https://github.com/rust-lang/rust/blob/1a87c49e33d87955e28fa92a8d59a17264ac6044/src/librustc_trait_selection/traits/select.rs#L2249-L2254).

**Comment by arora-aman** [comment]
Depends on #7

**Comment by m-hugo** [comment]
> Depends on #4

so #4 depends on #4?

**Comment by arora-aman** [comment]
> > Depends on #4
> 
> so #4 depends on #4? 

Oops. Fixed.

**Comment by arora-aman** [comment]
> > > Depends on #4
> > 
> > 
> > so #4 depends on #4?
> 
> Oops. Fixed.

This issue changes where we create the tuple of capture tys where #7 changes what is being captured. The code for both issues is in very close proximity of each other but this can be done separate from #7.

**Comment by nikomatsakis** [comment]
Update:

* We are always using tuples in auto trait selection and we have a hack to fix diagnostic (when we see a tuple, check if it the parent is a closure/generator and -- if so -- ignore it)
* async-await diagnostics is also working now, similar hack

**Comment by arora-aman** [comment]
closed by https://github.com/rust-lang/rust/pull/77873
