### ISSUE TITLE
Code sometimes uses `UniqueImmBorrow` and not `MutBorrow`

### ISSUE THREAD

**Issue by nikomatsakis** [rust-lang/project-rfc-2229#56]
Discussion here:

https://github.com/rust-lang/rust/pull/86995#discussion_r666814528

**Comment by nikomatsakis** [comment]
Relevant code:

https://github.com/rust-lang/rust/blob/efeea79a6bb6867b220471e0396b82b6b68ebc4c/compiler/rustc_typeck/src/check/upvar.rs#L1495-L1503

The problem here is that this code is still oriented around a single variable, and not a place.

**Comment by nikomatsakis** [comment]
Given `foo: &mut (u32, u32)`, there are a few scenarios to consider:

* If the closure mutates `foo.0` but we wind up capturing `foo`, we only need a "unique" borrow of `foo`.
* If the closure mutates `foo.0` *and we capture `foo.0`*, we need a "mut" borrow.

In short, the need for a "mut" borrow depends on what data we ultimately capture.

**Comment by arora-aman** [comment]
https://hackmd.io/dKtOGyJgSjuf-ztGD7I7kw
