### ISSUE TITLE
Let statement with wildcard lead to warnings for unused variables

### ISSUE THREAD

**Issue by roxelo** [rust-lang/project-rfc-2229#57]
There seem to be inconsistencies with lint warnings when using let statement with wildcards inside closures.

```rust
struct Props {
    field_1: u32, //~ WARNING: field is never read: `field_1`
    field_2: u32, //~ WARNING: field is never read: `field_2`
}

fn inside_closures() {
    let props_2 = Props { //~ WARNING: unused variable: `props_2`
        field_1: 1,
        field_2: 1,
    };

    let _ = || {
        let _: Props = props_2; // Warning lint does not consider `props_2` as being used here.
    };
}

fn ourside_closures() {
    let props_2 = Props {
        field_1: 1,
        field_2: 1,
    };

    let _: Props = props_2; // Warning lint does not consider `props_2` as being used here.
}
```

Note this same inconsistency takes place without type anotation.

**Comment by m-ou-se** [comment]
What's the state of this? Does this need to be fixed before we release Rust 2021?

**Comment by jyn514** [comment]
@roxelo how is this related to disjoint captures? Wouldn't the same warning occur either way?

**Comment by m-ou-se** [comment]
``warning: unused variable: `props_2` `` only shows up with `#![feature(capture_disjoint_fields)]` enabled.

**Comment by nikomatsakis** [comment]
So I looked into this a bit. Basically the problem is that we should consider all local variables that get  *mentioned* by the closure to be at least... read? That seems plausible. They may also be mutated/moved. Is the problem @roxelo that we are not taking "fake reads" into account?

**Comment by roxelo** [comment]
Yes, that's what Aman and I were thinking the issue was: https://rust-lang.zulipchat.com/#narrow/stream/189812-t-compiler.2Fwg-rfc-2229/topic/Lint.20warning.20inconsistencies/near/249786245. I'll try having a fix later tonight

**Comment by arora-aman** [comment]
I remember this now 😅

We had purposely decided to do it at one point I think.

Here is the relevant code https://github.com/rust-lang/rust/blob/master/compiler/rustc_passes/src/liveness.rs#L1243-L1249
