### ISSUE TITLE
Ensure minimal places are captured

### ISSUE THREAD

**Issue by arora-aman** [rust-lang/project-rfc-2229#9]
If we need to capture `a.b.c` and `a.b`, then we only capture `a.b`

With/After #7

**Comment by arora-aman** [comment]
During upvar analysis, we can keep a map from root variable to paths captured. As we see a new place that needs to be captured we can check if the root variable has a path that has been previously captured, if not just add it.

If the root variable has been captured we can iterate all captured paths and look for parent/child/sibling relations.
eg:


|    A       |    B            |             Relation                                            |      What we keep |
|-------  |---------- |------------------------------------------|-----------------|
| foo.x.y |  foo. x.z     |  A is sibling of B, since paths diverged     |          Both             |
| foo.x.y |  foo.m        |  A is sibling of B *, since paths diverged   |          Both             |
| foo.x    |  foo. x.z     |  A is parent of B                                          |            A                |
| foo.x.z  |  foo. x       |  A is child of B                                             |            B                |
| foo.x[20] |  foo. x[30]      |         A == B**                                     |        foo.x              |
| foo.x[20].p |  foo. x[30].q      |         A == B**                               |        foo.x              |
| foo.x |  foo. x[30]      |         A == B**                               |        foo.x              |


`*` `foo.x.y` and `foo.m` are not really siblings, but in our case it just indicates that we need to keep both 
`**` We can't differentiate b/w two different array elements as being disjoint


Initially we can store the information as a mapping from root variable to list of pairs, where each pair is `(Place, CaptureInfo)`.


To optimize answering these questions we can use [Tries](https://en.wikipedia.org/wiki/Trie), but that should be after we stabalize this. It might just add overhead because I don't think we will be capturing crazy long paths, though might be useful if the closure captures a lot of different paths starting at the same root variable.

We also need to be careful about borrow kinds 
eg:
```rust
let mut rect= Rectangle { top_left: Point { x: 10, y: 20 }, bottom_right: Point { x: 40, y: 50 } };
let c = || { 
      rect.top_left.x += 10;
      println!("{:?}", rect.top_left);
}
```

We will capture `rect.top_left.x` as mutable borrow and `rect.top_left` as immutable borrow. Overall we want to capture `rect.top_left` as mutable borrow. This would be similar as handling different kinds of use of the same place.

**Comment by nikomatsakis** [comment]
Status update in https://github.com/rust-lang/project-rfc-2229/issues/7#issuecomment-705696355
